CREATE ROLE openstack PASSWORD 'openstack' LOGIN;

CREATE DATABASE cinder;
CREATE DATABASE designate;
CREATE DATABASE glance;
CREATE DATABASE heat;
CREATE DATABASE keystone;
CREATE DATABASE neutron;
CREATE DATABASE nova;
CREATE DATABASE pdns;

GRANT ALL PRIVILEGES ON DATABASE cinder TO openstack;
GRANT ALL PRIVILEGES ON DATABASE designate TO openstack;
GRANT ALL PRIVILEGES ON DATABASE glance TO openstack;
GRANT ALL PRIVILEGES ON DATABASE heat TO openstack;
GRANT ALL PRIVILEGES ON DATABASE keystone TO openstack;
GRANT ALL PRIVILEGES ON DATABASE neutron TO openstack;
GRANT ALL PRIVILEGES ON DATABASE nova TO openstack;
GRANT ALL PRIVILEGES ON DATABASE pdns TO openstack;

