include ../../globals.mk

COMPONENT=postgres
BUILD_TAG=latest

DOCKER_RUN_OPTS=-e SERVICE_$(POSTGRES_PORT)_NAME=services/$(COMPONENT) \
				-e SERVICE_$(POSTGRES_PORT)_ID=url \
				-e POSTGRES_PASSWORD=$(POSTGRES_PASSWORD) \
				-e POSTGRES_USER=$(POSTGRES_USER) \
				-p $(POSTGRES_PORT):$(POSTGRES_PORT)
